TISA/TISA/Pages/Game/Achievements/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TISA.Models;
using TISA.Services;

namespace TISA.Pages.Game.Achievements
{
    public class IndexModel : PageModel
    {
        private readonly IAchievementService _achievementService;

        public ICollection<Achievement> Achievements { get; set; }
        public IndexModel(IAchievementService achievementService)
        {
            _achievementService = achievementService;
        }
        public async Task OnGetAsync()
        {
            Achievements = await _achievementService.GetAchievementsForPlayerAsync();
        }
    }
}

TISA/TISA/Pages/Game/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TISA.Pages.Game
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TISA/TISA/Pages/Game/PlayerInformation/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TISA.Models;
using TISA.Services;

namespace TISA.Pages.Game.PlayerInformation
{
    public class IndexModel : PageModel
    {
        private readonly IPlayerService _playerService;
        private readonly IItemService _itemService;

        public Player Player { get; set; }
        public ICollection<Item> PlayerInventory { get; set; }
        public bool PlayerHasItems => PlayerInventory.Count > 0;

        public IndexModel(IPlayerService playerService, IItemService itemService)
        {
            _playerService = playerService;
            _itemService = itemService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            if (!_playerService.IsPlayerDefined)
            {
                return NotFound();
            }

            Player = _playerService.Player;
            PlayerInventory = await _itemService.GetItemsForPlayerAsync();
            return Page();
        }
    }
}

TISA/TISA/Pages/Game/Quests/Finish.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TISA.Pages.Game
{
    public class FinishModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

TISA/TISA/Pages/Game/Quests/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TISA.Models;
using TISA.Services;

namespace TISA.Pages.Game.Quests
{
    public class IndexModel : PageModel
    {
        private readonly IQuestService _questService;

        public List<Quest> Quests { get; set; }

        public IndexModel(IQuestService questService)
        {
            _questService = questService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            Quests = (await _questService.GetAvailableQuestsForPlayerAsync()).ToList();
            if(Quests.Count == 0)
            {
                return RedirectToPage("Finish");
            }

            return Page();
        }
    }
}

TISA/TISA/Pages/Game/Quests/Quest.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TISA.Models;
using TISA.Services;

namespace TISA.Pages.Game.Quests
{
    public class QuestModel : PageModel
    {
        private readonly IQuestService _questService;

        public Quest Quest { get; set; }
        public QuestModel(IQuestService questService)
        {
            _questService = questService;
        }
        public async Task OnGetAsync(Guid questId)
        {
            Quest = await _questService.GetQuestByIdAsync(questId);
        }

        public async Task<IActionResult> OnPostAsync(Guid questId)
        {
            await _questService.CompleteQuestAsync(questId);
            return RedirectToPage("Index");
        }
    }
}

TISA/TISA/Pages/Game/Shop/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TISA.Models;
using TISA.Services;

namespace TISA.Pages.Game.Shop
{
    public class IndexModel : PageModel
    {
        private readonly IItemService _itemService;
        private readonly IPlayerService _playerService;

        public ICollection<Item> ShopItems { get; set; }
        public ICollection<Item> PlayerInventory { get; set; }

        public int PlayerGold { get; set; }
        
        [ModelBinder]
        public PostSellForm Form { get; set; }

        public IndexModel(IItemService itemService, IPlayerService playerService)
        {
            _itemService = itemService;
            _playerService = playerService;
        }
        public async Task OnGetAsync()
        {
            PlayerInventory = await _itemService.GetItemsForPlayerAsync();
            ShopItems = await _itemService.GetShopItemsAsync();
            PlayerGold = _playerService.Player.Gold;
        }

        public async Task<IActionResult> OnPostBuyAsync()
        {
            if (ModelState.IsValid)
            {
                await _itemService.BuyPlayerItem(Form.ItemId);
            }
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostSellAsync()
        {
            if (ModelState.IsValid)
            {
                await _itemService.SellPlayerItem(Form.ItemId);
            }
            return RedirectToPage();
        }

        public bool CanBuyItem(Item item)
        {
            return item.BuyPrice <= PlayerGold;
        }

        public class PostSellForm
        {
            [Required]
            public Guid ItemId { get; set; }
        }
    }
}

TISA/TISA/Pages/Game/Shop/Index.cshtml
@page
@model TISA.Pages.Game.Shop.IndexModel

@section Styles {
    <style>
        .shop__container {
            display: flex;
        }

            .shop__container > div {
                flex-grow: 1;
            }

                .shop__container > div > h3 {
                    text-align: center;
                }

            .shop__container .row {
                margin: 10px 0;
            }
    </style>
}
<div class="shop__container">
    <div style="flex-grow: 1;">
        <h3>Shopkeeper</h3>
        @foreach (var item in Model.ShopItems)
        {
            <form method="post" asp-page-handler="buy">
                <input type="hidden" asp-for="Form.ItemId" value="@item.Id" />
                <div class="row">
                    <span class="col-6">@item.Name</span>
                    <span class="col-4">@item.BuyPrice Gold</span>
                    <span class="col-2">
                        <button @(Model.CanBuyItem(item) ? string.Empty : "disabled") type="submit" class="btn btn-outline-primary btn-block">Buy</button>
                    </span>
                </div>
            </form>
        }
    </div>
    <div style="flex-grow: 1;">
        <h3><player-name /></h3>
        <p>@Model.PlayerGold gold</p>
        @foreach (var item in Model.PlayerInventory)
        {
            <form method="post" asp-page-handler="sell">
                <input type="hidden" asp-for="Form.ItemId" value="@item.Id" />
                <div class="row">
                    <span class="col-6">@item.Name</span>
                    <span class="col-4">@item.SellPrice Gold</span>
                    <span class="col-2">
                        <button type="submit" class="btn btn-outline-danger btn-block">Sell</button>
                    </span>
                </div>
            </form>
        }
    </div>
</div>
<a asp-page="../Index" class="btn btn-outline-secondary btn-block">Return to menu</a>